CREATE TABLE PARAMETERS (
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(100) NOT NULL,
    VALUE LONGTEXT NOT NULL,
    DT_REGISTER DATETIME NOT NULL,
    CONSTRAINT PK_PARAMETERS PRIMARY KEY (ID)
);
