CREATE TABLE SEQUENCES
(
  NM_SEQUENCE VARCHAR(32) NOT NULL UNIQUE,
  VL_SEQUENCE BIGINT      NOT NULL
);

INSERT INTO SEQUENCES(NM_SEQUENCE, VL_SEQUENCE) VALUES('USER_REGISTRATION_SEQ', 9999);

DELIMITER :)
CREATE FUNCTION GetSequenceVal( sSeqName VARCHAR(32), iIncrement INTEGER )
RETURNS BIGINT
BEGIN
  DECLARE iSeqValue BIGINT;

  SELECT VL_SEQUENCE FROM SEQUENCES
  WHERE  ( NM_SEQUENCE = sSeqName )
  INTO   @iSeqValue;

  IF ( iIncrement <> 0 ) THEN
    SET @iSeqValue = @iSeqValue + iIncrement;

    UPDATE SEQUENCES SET VL_SEQUENCE = @iSeqValue
    WHERE  ( NM_SEQUENCE = sSeqName );
  END IF;

  RETURN @iSeqValue;
END :)
DELIMITER ;
